# Permalinks
permalink:        pretty

# Settings
gems:             [jekyll-paginate]
markdown:         kramdown
destination:      ./_gh_pages
exclude:          ["README.md"]
paginate:         10
encoding:         UTF-8
future:           false
name:             Built With Ember
url:              http://builtwithember.io
description:      "Ambitious web applications built using Ember.js."
